services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: faq_api
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://admin:pass@db:5432/faqdb
      GOOGLE_APPLICATION_CREDENTIALS: /app/gcp_cred.json
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/app  # Enable syncing between host and container

  db:
    image: postgres:13
    container_name: faq_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: faqdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Attach persistent storage

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"

volumes:
  postgres_data:  # Define the named volume
