services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: faq_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app  # Enable syncing between host and container

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: faqdb
    ports:
      - "5432:5432"
